# Generated by Django 4.0.4 on 2022-04-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minifilmweb', '0003_film_imdb_rating_film_opis_film_plakat_film_premiera'),
    ]

    operations = [
        migrations.CreateModel(
            name='DodatkoweInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.PositiveSmallIntegerField(default=0)),
                ('gatunek', models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (4, 'Dramat'), (1, 'Horror'), (0, 'Inne'), (2, 'Komedia')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='dodatkowe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minifilmweb.dodatkoweinfo'),
        ),
    ]
